"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PancakeRoundIcon = exports.PancakesIcon = exports.OpenNewIcon = exports.NoProfileAvatarIcon = exports.MinusIcon = exports.MetamaskIcon = exports.MedalTealIcon = exports.MedalSilverIcon = exports.MedalPurpleIcon = exports.MedalGoldIcon = exports.MedalBronzeIcon = exports.LogoRoundIcon = exports.LogoIcon = exports.ListViewIcon = exports.LaurelRightIcon = exports.LaurelLeftIcon = exports.LanguageIcon = exports.InfoIcon = exports.HistoryIcon = exports.HelpIcon = exports.ErrorIcon = exports.CrownIcon = exports.CopyIcon = exports.CommunityIcon = exports.CogIcon = exports.CloseIcon = exports.ChevronUpIcon = exports.ChevronRightIcon = exports.ChevronLeftIcon = exports.ChevronDownIcon = exports.CheckmarkCircleIcon = exports.CheckmarkIcon = exports.ChartIcon = exports.CircleOutlineIcon = exports.CalculateIcon = exports.CardViewIcon = exports.Cards = exports.BunnyPlaceholderIcon = exports.BunnyCardsIcon = exports.BnbUsdtPairTokenIcon = exports.BlockIcon = exports.BinanceIcon = exports.AutoRenewIcon = exports.ArrowUpIcon = exports.ArrowForwardIcon = exports.ArrowDropUpIcon = exports.ArrowDropDownIcon = exports.ArrowDownIcon = exports.ArrowBackIcon = exports.AddIcon = void 0;
exports.Svg = exports.RefreshIcon = exports.WarningIcon = exports.VoteIcon = exports.VolumeUpIcon = exports.VolumeOffIcon = exports.VisibilityOn = exports.VisibilityOff = exports.SyncAltIcon = exports.SwapVertIcon = exports.StarLineIcon = exports.StarFillIcon = exports.SearchIcon = exports.TuneIcon = exports.TrophyGoldIcon = exports.TimerIcon = exports.TicketRound = exports.Ticket = exports.TestnetIcon = exports.TeamPlayerIcon = exports.PresentNoneIcon = exports.PresentWonIcon = exports.PresentCheckIcon = exports.WaitIcon = exports.ProgressBunny = exports.VerifiedIcon = exports.RemoveIcon = exports.ProposalIcon = exports.PrizeIcon = exports.PlayCircleOutlineIcon = exports.PocketWatchIcon = void 0;
var Add_1 = require("./Icons/Add");
Object.defineProperty(exports, "AddIcon", { enumerable: true, get: function () { return Add_1.default; } });
var ArrowBack_1 = require("./Icons/ArrowBack");
Object.defineProperty(exports, "ArrowBackIcon", { enumerable: true, get: function () { return ArrowBack_1.default; } });
var ArrowDown_1 = require("./Icons/ArrowDown");
Object.defineProperty(exports, "ArrowDownIcon", { enumerable: true, get: function () { return ArrowDown_1.default; } });
var ArrowDropDown_1 = require("./Icons/ArrowDropDown");
Object.defineProperty(exports, "ArrowDropDownIcon", { enumerable: true, get: function () { return ArrowDropDown_1.default; } });
var ArrowDropUp_1 = require("./Icons/ArrowDropUp");
Object.defineProperty(exports, "ArrowDropUpIcon", { enumerable: true, get: function () { return ArrowDropUp_1.default; } });
var ArrowForward_1 = require("./Icons/ArrowForward");
Object.defineProperty(exports, "ArrowForwardIcon", { enumerable: true, get: function () { return ArrowForward_1.default; } });
var ArrowUp_1 = require("./Icons/ArrowUp");
Object.defineProperty(exports, "ArrowUpIcon", { enumerable: true, get: function () { return ArrowUp_1.default; } });
var AutoRenew_1 = require("./Icons/AutoRenew");
Object.defineProperty(exports, "AutoRenewIcon", { enumerable: true, get: function () { return AutoRenew_1.default; } });
var Binance_1 = require("./Icons/Binance");
Object.defineProperty(exports, "BinanceIcon", { enumerable: true, get: function () { return Binance_1.default; } });
var Block_1 = require("./Icons/Block");
Object.defineProperty(exports, "BlockIcon", { enumerable: true, get: function () { return Block_1.default; } });
var BnbUsdtPairToken_1 = require("./Icons/BnbUsdtPairToken");
Object.defineProperty(exports, "BnbUsdtPairTokenIcon", { enumerable: true, get: function () { return BnbUsdtPairToken_1.default; } });
var BunnyCards_1 = require("./Icons/BunnyCards");
Object.defineProperty(exports, "BunnyCardsIcon", { enumerable: true, get: function () { return BunnyCards_1.default; } });
var BunnyPlaceholder_1 = require("./Icons/BunnyPlaceholder");
Object.defineProperty(exports, "BunnyPlaceholderIcon", { enumerable: true, get: function () { return BunnyPlaceholder_1.default; } });
var Cards_1 = require("./Icons/Cards");
Object.defineProperty(exports, "Cards", { enumerable: true, get: function () { return Cards_1.default; } });
var CardView_1 = require("./Icons/CardView");
Object.defineProperty(exports, "CardViewIcon", { enumerable: true, get: function () { return CardView_1.default; } });
var Calculate_1 = require("./Icons/Calculate");
Object.defineProperty(exports, "CalculateIcon", { enumerable: true, get: function () { return Calculate_1.default; } });
var CircleOutline_1 = require("./Icons/CircleOutline");
Object.defineProperty(exports, "CircleOutlineIcon", { enumerable: true, get: function () { return CircleOutline_1.default; } });
var Chart_1 = require("./Icons/Chart");
Object.defineProperty(exports, "ChartIcon", { enumerable: true, get: function () { return Chart_1.default; } });
var Checkmark_1 = require("./Icons/Checkmark");
Object.defineProperty(exports, "CheckmarkIcon", { enumerable: true, get: function () { return Checkmark_1.default; } });
var CheckmarkCircle_1 = require("./Icons/CheckmarkCircle");
Object.defineProperty(exports, "CheckmarkCircleIcon", { enumerable: true, get: function () { return CheckmarkCircle_1.default; } });
var ChevronDown_1 = require("./Icons/ChevronDown");
Object.defineProperty(exports, "ChevronDownIcon", { enumerable: true, get: function () { return ChevronDown_1.default; } });
var ChevronLeft_1 = require("./Icons/ChevronLeft");
Object.defineProperty(exports, "ChevronLeftIcon", { enumerable: true, get: function () { return ChevronLeft_1.default; } });
var ChevronRight_1 = require("./Icons/ChevronRight");
Object.defineProperty(exports, "ChevronRightIcon", { enumerable: true, get: function () { return ChevronRight_1.default; } });
var ChevronUp_1 = require("./Icons/ChevronUp");
Object.defineProperty(exports, "ChevronUpIcon", { enumerable: true, get: function () { return ChevronUp_1.default; } });
var Close_1 = require("./Icons/Close");
Object.defineProperty(exports, "CloseIcon", { enumerable: true, get: function () { return Close_1.default; } });
var Cog_1 = require("./Icons/Cog");
Object.defineProperty(exports, "CogIcon", { enumerable: true, get: function () { return Cog_1.default; } });
var Community_1 = require("./Icons/Community");
Object.defineProperty(exports, "CommunityIcon", { enumerable: true, get: function () { return Community_1.default; } });
var Copy_1 = require("./Icons/Copy");
Object.defineProperty(exports, "CopyIcon", { enumerable: true, get: function () { return Copy_1.default; } });
var Crown_1 = require("./Icons/Crown");
Object.defineProperty(exports, "CrownIcon", { enumerable: true, get: function () { return Crown_1.default; } });
var Error_1 = require("./Icons/Error");
Object.defineProperty(exports, "ErrorIcon", { enumerable: true, get: function () { return Error_1.default; } });
var Help_1 = require("./Icons/Help");
Object.defineProperty(exports, "HelpIcon", { enumerable: true, get: function () { return Help_1.default; } });
var History_1 = require("./Icons/History");
Object.defineProperty(exports, "HistoryIcon", { enumerable: true, get: function () { return History_1.default; } });
var Info_1 = require("./Icons/Info");
Object.defineProperty(exports, "InfoIcon", { enumerable: true, get: function () { return Info_1.default; } });
var Language_1 = require("./Icons/Language");
Object.defineProperty(exports, "LanguageIcon", { enumerable: true, get: function () { return Language_1.default; } });
var LaurelLeft_1 = require("./Icons/LaurelLeft");
Object.defineProperty(exports, "LaurelLeftIcon", { enumerable: true, get: function () { return LaurelLeft_1.default; } });
var LaurelRight_1 = require("./Icons/LaurelRight");
Object.defineProperty(exports, "LaurelRightIcon", { enumerable: true, get: function () { return LaurelRight_1.default; } });
var ListView_1 = require("./Icons/ListView");
Object.defineProperty(exports, "ListViewIcon", { enumerable: true, get: function () { return ListView_1.default; } });
var Logo_1 = require("./Icons/Logo");
Object.defineProperty(exports, "LogoIcon", { enumerable: true, get: function () { return Logo_1.default; } });
var LogoRound_1 = require("./Icons/LogoRound");
Object.defineProperty(exports, "LogoRoundIcon", { enumerable: true, get: function () { return LogoRound_1.default; } });
var MedalBronze_1 = require("./Icons/MedalBronze");
Object.defineProperty(exports, "MedalBronzeIcon", { enumerable: true, get: function () { return MedalBronze_1.default; } });
var MedalGold_1 = require("./Icons/MedalGold");
Object.defineProperty(exports, "MedalGoldIcon", { enumerable: true, get: function () { return MedalGold_1.default; } });
var MedalPurple_1 = require("./Icons/MedalPurple");
Object.defineProperty(exports, "MedalPurpleIcon", { enumerable: true, get: function () { return MedalPurple_1.default; } });
var MedalSilver_1 = require("./Icons/MedalSilver");
Object.defineProperty(exports, "MedalSilverIcon", { enumerable: true, get: function () { return MedalSilver_1.default; } });
var MedalTeal_1 = require("./Icons/MedalTeal");
Object.defineProperty(exports, "MedalTealIcon", { enumerable: true, get: function () { return MedalTeal_1.default; } });
var Metamask_1 = require("./Icons/Metamask");
Object.defineProperty(exports, "MetamaskIcon", { enumerable: true, get: function () { return Metamask_1.default; } });
var Minus_1 = require("./Icons/Minus");
Object.defineProperty(exports, "MinusIcon", { enumerable: true, get: function () { return Minus_1.default; } });
var NoProfileAvatar_1 = require("./Icons/NoProfileAvatar");
Object.defineProperty(exports, "NoProfileAvatarIcon", { enumerable: true, get: function () { return NoProfileAvatar_1.default; } });
var OpenNew_1 = require("./Icons/OpenNew");
Object.defineProperty(exports, "OpenNewIcon", { enumerable: true, get: function () { return OpenNew_1.default; } });
var Pancakes_1 = require("./Icons/Pancakes");
Object.defineProperty(exports, "PancakesIcon", { enumerable: true, get: function () { return Pancakes_1.default; } });
var PancakeRound_1 = require("./Icons/PancakeRound");
Object.defineProperty(exports, "PancakeRoundIcon", { enumerable: true, get: function () { return PancakeRound_1.default; } });
var PocketWatch_1 = require("./Icons/PocketWatch");
Object.defineProperty(exports, "PocketWatchIcon", { enumerable: true, get: function () { return PocketWatch_1.default; } });
var PlayCircleOutline_1 = require("./Icons/PlayCircleOutline");
Object.defineProperty(exports, "PlayCircleOutlineIcon", { enumerable: true, get: function () { return PlayCircleOutline_1.default; } });
var Prize_1 = require("./Icons/Prize");
Object.defineProperty(exports, "PrizeIcon", { enumerable: true, get: function () { return Prize_1.default; } });
var Proposal_1 = require("./Icons/Proposal");
Object.defineProperty(exports, "ProposalIcon", { enumerable: true, get: function () { return Proposal_1.default; } });
var Remove_1 = require("./Icons/Remove");
Object.defineProperty(exports, "RemoveIcon", { enumerable: true, get: function () { return Remove_1.default; } });
var Verified_1 = require("./Icons/Verified");
Object.defineProperty(exports, "VerifiedIcon", { enumerable: true, get: function () { return Verified_1.default; } });
var ProgressBunny_1 = require("./Icons/ProgressBunny");
Object.defineProperty(exports, "ProgressBunny", { enumerable: true, get: function () { return ProgressBunny_1.default; } });
var Wait_1 = require("./Icons/Wait");
Object.defineProperty(exports, "WaitIcon", { enumerable: true, get: function () { return Wait_1.default; } });
var PresentCheck_1 = require("./Icons/PresentCheck");
Object.defineProperty(exports, "PresentCheckIcon", { enumerable: true, get: function () { return PresentCheck_1.default; } });
var PresentWon_1 = require("./Icons/PresentWon");
Object.defineProperty(exports, "PresentWonIcon", { enumerable: true, get: function () { return PresentWon_1.default; } });
var PresentNone_1 = require("./Icons/PresentNone");
Object.defineProperty(exports, "PresentNoneIcon", { enumerable: true, get: function () { return PresentNone_1.default; } });
var TeamPlayer_1 = require("./Icons/TeamPlayer");
Object.defineProperty(exports, "TeamPlayerIcon", { enumerable: true, get: function () { return TeamPlayer_1.default; } });
var Testnet_1 = require("./Icons/Testnet");
Object.defineProperty(exports, "TestnetIcon", { enumerable: true, get: function () { return Testnet_1.default; } });
var Ticket_1 = require("./Icons/Ticket");
Object.defineProperty(exports, "Ticket", { enumerable: true, get: function () { return Ticket_1.default; } });
var TicketRound_1 = require("./Icons/TicketRound");
Object.defineProperty(exports, "TicketRound", { enumerable: true, get: function () { return TicketRound_1.default; } });
var Timer_1 = require("./Icons/Timer");
Object.defineProperty(exports, "TimerIcon", { enumerable: true, get: function () { return Timer_1.default; } });
var TrophyGold_1 = require("./Icons/TrophyGold");
Object.defineProperty(exports, "TrophyGoldIcon", { enumerable: true, get: function () { return TrophyGold_1.default; } });
var Tune_1 = require("./Icons/Tune");
Object.defineProperty(exports, "TuneIcon", { enumerable: true, get: function () { return Tune_1.default; } });
var Search_1 = require("./Icons/Search");
Object.defineProperty(exports, "SearchIcon", { enumerable: true, get: function () { return Search_1.default; } });
var StarFill_1 = require("./Icons/StarFill");
Object.defineProperty(exports, "StarFillIcon", { enumerable: true, get: function () { return StarFill_1.default; } });
var StarLine_1 = require("./Icons/StarLine");
Object.defineProperty(exports, "StarLineIcon", { enumerable: true, get: function () { return StarLine_1.default; } });
var SwapVert_1 = require("./Icons/SwapVert");
Object.defineProperty(exports, "SwapVertIcon", { enumerable: true, get: function () { return SwapVert_1.default; } });
var SyncAlt_1 = require("./Icons/SyncAlt");
Object.defineProperty(exports, "SyncAltIcon", { enumerable: true, get: function () { return SyncAlt_1.default; } });
var VisibilityOff_1 = require("./Icons/VisibilityOff");
Object.defineProperty(exports, "VisibilityOff", { enumerable: true, get: function () { return VisibilityOff_1.default; } });
var VisibilityOn_1 = require("./Icons/VisibilityOn");
Object.defineProperty(exports, "VisibilityOn", { enumerable: true, get: function () { return VisibilityOn_1.default; } });
var VolumeOff_1 = require("./Icons/VolumeOff");
Object.defineProperty(exports, "VolumeOffIcon", { enumerable: true, get: function () { return VolumeOff_1.default; } });
var VolumeUp_1 = require("./Icons/VolumeUp");
Object.defineProperty(exports, "VolumeUpIcon", { enumerable: true, get: function () { return VolumeUp_1.default; } });
var Vote_1 = require("./Icons/Vote");
Object.defineProperty(exports, "VoteIcon", { enumerable: true, get: function () { return Vote_1.default; } });
var Warning_1 = require("./Icons/Warning");
Object.defineProperty(exports, "WarningIcon", { enumerable: true, get: function () { return Warning_1.default; } });
var Refresh_1 = require("./Icons/Refresh");
Object.defineProperty(exports, "RefreshIcon", { enumerable: true, get: function () { return Refresh_1.default; } });
var Svg_1 = require("./Svg");
Object.defineProperty(exports, "Svg", { enumerable: true, get: function () { return Svg_1.default; } });
