"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TwitterIcon = exports.TradeIcon = exports.TicketIcon = exports.TelegramIcon = exports.TeamBattleIcon = exports.SunIcon = exports.PredictionsIcon = exports.PoolIcon = exports.NftIcon = exports.MoreIcon = exports.MoonIcon = exports.LogoIcon = exports.InfoIcon = exports.IfoIcon = exports.HomeIcon = exports.HamburgerCloseIcon = exports.HamburgerIcon = exports.GroupsIcon = exports.FarmIcon = void 0;
var Farm_1 = require("./Farm");
Object.defineProperty(exports, "FarmIcon", { enumerable: true, get: function () { return Farm_1.default; } });
var Groups_1 = require("./Groups");
Object.defineProperty(exports, "GroupsIcon", { enumerable: true, get: function () { return Groups_1.default; } });
var Hamburger_1 = require("./Hamburger");
Object.defineProperty(exports, "HamburgerIcon", { enumerable: true, get: function () { return Hamburger_1.default; } });
var HamburgerClose_1 = require("./HamburgerClose");
Object.defineProperty(exports, "HamburgerCloseIcon", { enumerable: true, get: function () { return HamburgerClose_1.default; } });
var Home_1 = require("./Home");
Object.defineProperty(exports, "HomeIcon", { enumerable: true, get: function () { return Home_1.default; } });
var Ifo_1 = require("./Ifo");
Object.defineProperty(exports, "IfoIcon", { enumerable: true, get: function () { return Ifo_1.default; } });
var Info_1 = require("./Info");
Object.defineProperty(exports, "InfoIcon", { enumerable: true, get: function () { return Info_1.default; } });
var Logo_1 = require("./Logo");
Object.defineProperty(exports, "LogoIcon", { enumerable: true, get: function () { return Logo_1.default; } });
var Moon_1 = require("./Moon");
Object.defineProperty(exports, "MoonIcon", { enumerable: true, get: function () { return Moon_1.default; } });
var More_1 = require("./More");
Object.defineProperty(exports, "MoreIcon", { enumerable: true, get: function () { return More_1.default; } });
var Nft_1 = require("./Nft");
Object.defineProperty(exports, "NftIcon", { enumerable: true, get: function () { return Nft_1.default; } });
var Pool_1 = require("./Pool");
Object.defineProperty(exports, "PoolIcon", { enumerable: true, get: function () { return Pool_1.default; } });
var Predictions_1 = require("./Predictions");
Object.defineProperty(exports, "PredictionsIcon", { enumerable: true, get: function () { return Predictions_1.default; } });
var Sun_1 = require("./Sun");
Object.defineProperty(exports, "SunIcon", { enumerable: true, get: function () { return Sun_1.default; } });
var TeamBattle_1 = require("./TeamBattle");
Object.defineProperty(exports, "TeamBattleIcon", { enumerable: true, get: function () { return TeamBattle_1.default; } });
var Telegram_1 = require("./Telegram");
Object.defineProperty(exports, "TelegramIcon", { enumerable: true, get: function () { return Telegram_1.default; } });
var Ticket_1 = require("./Ticket");
Object.defineProperty(exports, "TicketIcon", { enumerable: true, get: function () { return Ticket_1.default; } });
var Trade_1 = require("./Trade");
Object.defineProperty(exports, "TradeIcon", { enumerable: true, get: function () { return Trade_1.default; } });
var Twitter_1 = require("./Twitter");
Object.defineProperty(exports, "TwitterIcon", { enumerable: true, get: function () { return Twitter_1.default; } });
