"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
var testHelpers_1 = require("../../testHelpers");
var BalanceInput_1 = require("../../components/BalanceInput/BalanceInput");
var handleChange = jest.fn();
it("renders correctly", function () {
    var asFragment = testHelpers_1.renderWithTheme(<BalanceInput_1.default value="14" currencyValue="15 USD" onUserInput={handleChange}/>).asFragment;
    expect(asFragment()).toMatchInlineSnapshot("\n    <DocumentFragment>\n      .c3 {\n      color: #7A6EAA;\n      font-size: 12px;\n      font-weight: 400;\n      line-height: 1.5;\n      font-size: 12px;\n      text-align: right;\n    }\n\n    .c1 {\n      background-color: #eeeaf4;\n      border: 0;\n      border-radius: 16px;\n      box-shadow: inset 0px 2px 2px -1px rgba(74,74,104,0.1);\n      color: #280D5F;\n      display: block;\n      font-size: 16px;\n      height: 40px;\n      outline: 0;\n      padding: 0 16px;\n      width: 100%;\n    }\n\n    .c1::-webkit-input-placeholder {\n      color: #7A6EAA;\n    }\n\n    .c1::-moz-placeholder {\n      color: #7A6EAA;\n    }\n\n    .c1:-ms-input-placeholder {\n      color: #7A6EAA;\n    }\n\n    .c1::placeholder {\n      color: #7A6EAA;\n    }\n\n    .c1:disabled {\n      background-color: #E9EAEB;\n      box-shadow: none;\n      color: #BDC2C4;\n      cursor: not-allowed;\n    }\n\n    .c1:focus:not(:disabled) {\n      box-shadow: 0px 0px 0px 1px #7645D9,0px 0px 0px 4px rgba(118,69,217,0.6);\n    }\n\n    .c0 {\n      background-color: #eeeaf4;\n      border: 1px solid #d7caec;\n      border-radius: 16px;\n      box-shadow: inset 0px 2px 2px -1px rgba(74,74,104,0.1);\n      padding: 8px 16px;\n    }\n\n    .c2 {\n      background: transparent;\n      border-radius: 0;\n      box-shadow: none;\n      padding-left: 0;\n      padding-right: 0;\n      text-align: right;\n    }\n\n    .c2::-webkit-input-placeholder {\n      color: #7A6EAA;\n    }\n\n    .c2::-moz-placeholder {\n      color: #7A6EAA;\n    }\n\n    .c2:-ms-input-placeholder {\n      color: #7A6EAA;\n    }\n\n    .c2::placeholder {\n      color: #7A6EAA;\n    }\n\n    .c2:focus:not(:disabled) {\n      box-shadow: none;\n    }\n\n    <div\n        class=\"c0\"\n      >\n        <input\n          class=\"c1 c2\"\n          inputmode=\"decimal\"\n          min=\"0\"\n          pattern=\"^[0-9]*[.,]?[0-9]{0,18}$\"\n          placeholder=\"0.0\"\n          scale=\"md\"\n          value=\"14\"\n        />\n        <div\n          class=\"c3\"\n          color=\"textSubtle\"\n          font-size=\"12px\"\n        >\n          15 USD\n        </div>\n      </div>\n    </DocumentFragment>\n  ");
});
