"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
var testHelpers_1 = require("../../testHelpers");
var Button_1 = require("../../components/Button/Button");
it("renders correctly", function () {
    var asFragment = testHelpers_1.renderWithTheme(<Button_1.default>Submit</Button_1.default>).asFragment;
    expect(asFragment()).toMatchInlineSnapshot("\n    <DocumentFragment>\n      .c0 {\n      -webkit-align-items: center;\n      -webkit-box-align: center;\n      -ms-flex-align: center;\n      align-items: center;\n      border: 0;\n      border-radius: 16px;\n      box-shadow: 0px -1px 0px 0px rgba(14,14,44,0.4) inset;\n      cursor: pointer;\n      display: -webkit-inline-box;\n      display: -webkit-inline-flex;\n      display: -ms-inline-flexbox;\n      display: inline-flex;\n      font-family: inherit;\n      font-size: 16px;\n      font-weight: 600;\n      -webkit-box-pack: center;\n      -webkit-justify-content: center;\n      -ms-flex-pack: center;\n      justify-content: center;\n      -webkit-letter-spacing: 0.03em;\n      -moz-letter-spacing: 0.03em;\n      -ms-letter-spacing: 0.03em;\n      letter-spacing: 0.03em;\n      line-height: 1;\n      opacity: 1;\n      outline: 0;\n      -webkit-transition: background-color 0.2s,opacity 0.2s;\n      transition: background-color 0.2s,opacity 0.2s;\n      height: 48px;\n      padding: 0 24px;\n      background-color: #1FC7D4;\n      color: white;\n    }\n\n    .c0:hover:not(:disabled):not(.pancake-button--disabled):not(.pancake-button--disabled):not(:active) {\n      opacity: 0.65;\n    }\n\n    .c0:active:not(:disabled):not(.pancake-button--disabled):not(.pancake-button--disabled) {\n      opacity: 0.85;\n      -webkit-transform: translateY(1px);\n      -ms-transform: translateY(1px);\n      transform: translateY(1px);\n      box-shadow: none;\n    }\n\n    .c0:disabled,\n    .c0.pancake-button--disabled {\n      background-color: #E9EAEB;\n      border-color: #E9EAEB;\n      box-shadow: none;\n      color: #BDC2C4;\n      cursor: not-allowed;\n    }\n\n    <button\n        class=\"c0\"\n        scale=\"md\"\n      >\n        Submit\n      </button>\n    </DocumentFragment>\n  ");
});
