"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
var testHelpers_1 = require("../../testHelpers");
var Checkbox_1 = require("../../components/Checkbox/Checkbox");
var handleChange = jest.fn();
it("renders correctly", function () {
    var asFragment = (0, testHelpers_1.renderWithTheme)(<Checkbox_1.default checked onChange={handleChange}/>).asFragment;
    expect(asFragment()).toMatchInlineSnapshot("\n    <DocumentFragment>\n      .c0 {\n      -webkit-appearance: none;\n      -moz-appearance: none;\n      appearance: none;\n      overflow: hidden;\n      cursor: pointer;\n      position: relative;\n      display: inline-block;\n      height: 32px;\n      width: 32px;\n      vertical-align: middle;\n      -webkit-transition: background-color 0.2s ease-in-out;\n      transition: background-color 0.2s ease-in-out;\n      border: 0;\n      border-radius: 8px;\n      background-color: #eeeaf4;\n      box-shadow: inset 0px 2px 2px -1px rgba(74,74,104,0.1);\n    }\n\n    .c0:after {\n      content: \"\";\n      position: absolute;\n      border-bottom: 2px solid;\n      border-left: 2px solid;\n      border-color: transparent;\n      top: 30%;\n      left: 0;\n      right: 0;\n      width: 50%;\n      height: 25%;\n      margin: auto;\n      -webkit-transform: rotate(-50deg);\n      -ms-transform: rotate(-50deg);\n      transform: rotate(-50deg);\n      -webkit-transition: border-color 0.2s ease-in-out;\n      transition: border-color 0.2s ease-in-out;\n    }\n\n    .c0:hover:not(:disabled):not(:checked) {\n      box-shadow: 0px 0px 0px 1px #7645D9,0px 0px 0px 4px rgba(118,69,217,0.6);\n    }\n\n    .c0:focus {\n      outline: none;\n      box-shadow: 0px 0px 0px 1px #7645D9,0px 0px 0px 4px rgba(118,69,217,0.6);\n    }\n\n    .c0:checked {\n      background-color: #31D0AA;\n    }\n\n    .c0:checked:after {\n      border-color: white;\n    }\n\n    .c0:disabled {\n      cursor: default;\n      opacity: 0.6;\n    }\n\n    <input\n        checked=\"\"\n        class=\"c0\"\n        scale=\"md\"\n        type=\"checkbox\"\n      />\n    </DocumentFragment>\n  ");
});
