"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
var testHelpers_1 = require("../../testHelpers");
var Toggle_1 = require("../../components/Toggle/Toggle");
var handleChange = jest.fn();
it("renders correctly", function () {
    var asFragment = testHelpers_1.renderWithTheme(<Toggle_1.default checked onChange={handleChange} scale="md"/>).asFragment;
    expect(asFragment()).toMatchInlineSnapshot("\n    <DocumentFragment>\n      .c3 {\n      background-color: #FFFFFF;\n      border-radius: 50%;\n      cursor: pointer;\n      height: 32px;\n      left: 4px;\n      position: absolute;\n      top: 4px;\n      -webkit-transition: left 200ms ease-in;\n      transition: left 200ms ease-in;\n      width: 32px;\n      z-index: 1;\n    }\n\n    .c1 {\n      cursor: pointer;\n      opacity: 0;\n      height: 100%;\n      position: absolute;\n      width: 100%;\n      z-index: 3;\n    }\n\n    .c1:checked + .c2 {\n      left: calc(100% - 36px);\n    }\n\n    .c1:focus + .c2 {\n      box-shadow: 0px 0px 0px 1px #7645D9,0px 0px 0px 4px rgba(118,69,217,0.6);\n    }\n\n    .c1:hover + .c2:not(:disabled):not(:checked) {\n      box-shadow: 0px 0px 0px 1px #7645D9,0px 0px 0px 4px rgba(118,69,217,0.6);\n    }\n\n    .c0 {\n      -webkit-align-items: center;\n      -webkit-box-align: center;\n      -ms-flex-align: center;\n      align-items: center;\n      background-color: #31D0AA;\n      border-radius: 24px;\n      box-shadow: inset 0px 2px 2px -1px rgba(74,74,104,0.1);\n      cursor: pointer;\n      display: -webkit-inline-box;\n      display: -webkit-inline-flex;\n      display: -ms-inline-flexbox;\n      display: inline-flex;\n      height: 40px;\n      position: relative;\n      -webkit-transition: background-color 200ms;\n      transition: background-color 200ms;\n      width: 72px;\n    }\n\n    <div\n        class=\"c0\"\n        scale=\"md\"\n      >\n        <input\n          checked=\"\"\n          class=\"c1\"\n          scale=\"md\"\n          type=\"checkbox\"\n        />\n        <div\n          class=\"c2 c3\"\n          scale=\"md\"\n        />\n      </div>\n    </DocumentFragment>\n  ");
});
it("renders correctly scale sm", function () {
    var asFragment = testHelpers_1.renderWithTheme(<Toggle_1.default checked onChange={handleChange} scale="sm"/>).asFragment;
    expect(asFragment()).toMatchInlineSnapshot("\n    <DocumentFragment>\n      .c3 {\n      background-color: #FFFFFF;\n      border-radius: 50%;\n      cursor: pointer;\n      height: 16px;\n      left: 2px;\n      position: absolute;\n      top: 2px;\n      -webkit-transition: left 200ms ease-in;\n      transition: left 200ms ease-in;\n      width: 16px;\n      z-index: 1;\n    }\n\n    .c1 {\n      cursor: pointer;\n      opacity: 0;\n      height: 100%;\n      position: absolute;\n      width: 100%;\n      z-index: 3;\n    }\n\n    .c1:checked + .c2 {\n      left: calc(100% - 18px);\n    }\n\n    .c1:focus + .c2 {\n      box-shadow: 0px 0px 0px 1px #7645D9,0px 0px 0px 4px rgba(118,69,217,0.6);\n    }\n\n    .c1:hover + .c2:not(:disabled):not(:checked) {\n      box-shadow: 0px 0px 0px 1px #7645D9,0px 0px 0px 4px rgba(118,69,217,0.6);\n    }\n\n    .c0 {\n      -webkit-align-items: center;\n      -webkit-box-align: center;\n      -ms-flex-align: center;\n      align-items: center;\n      background-color: #31D0AA;\n      border-radius: 24px;\n      box-shadow: inset 0px 2px 2px -1px rgba(74,74,104,0.1);\n      cursor: pointer;\n      display: -webkit-inline-box;\n      display: -webkit-inline-flex;\n      display: -ms-inline-flexbox;\n      display: inline-flex;\n      height: 20px;\n      position: relative;\n      -webkit-transition: background-color 200ms;\n      transition: background-color 200ms;\n      width: 36px;\n    }\n\n    <div\n        class=\"c0\"\n        scale=\"sm\"\n      >\n        <input\n          checked=\"\"\n          class=\"c1\"\n          scale=\"sm\"\n          type=\"checkbox\"\n        />\n        <div\n          class=\"c2 c3\"\n          scale=\"sm\"\n        />\n      </div>\n    </DocumentFragment>\n  ");
});
